// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package billing

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SERVICE_TYPE int32

const (
	SERVICE_TYPE_WATER       SERVICE_TYPE = 0
	SERVICE_TYPE_SEWER       SERVICE_TYPE = 1
	SERVICE_TYPE_ELECTRICITY SERVICE_TYPE = 2
	SERVICE_TYPE_GAS         SERVICE_TYPE = 3
	SERVICE_TYPE_HYDRANT     SERVICE_TYPE = 4
	SERVICE_TYPE_FIRE        SERVICE_TYPE = 5
)

var SERVICE_TYPE_name = map[int32]string{
	0: "WATER",
	1: "SEWER",
	2: "ELECTRICITY",
	3: "GAS",
	4: "HYDRANT",
	5: "FIRE",
}

var SERVICE_TYPE_value = map[string]int32{
	"WATER":       0,
	"SEWER":       1,
	"ELECTRICITY": 2,
	"GAS":         3,
	"HYDRANT":     4,
	"FIRE":        5,
}

func (x SERVICE_TYPE) Enum() *SERVICE_TYPE {
	p := new(SERVICE_TYPE)
	*p = x
	return p
}

func (x SERVICE_TYPE) String() string {
	return proto.EnumName(SERVICE_TYPE_name, int32(x))
}

func (x *SERVICE_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SERVICE_TYPE_value, data, "SERVICE_TYPE")
	if err != nil {
		return err
	}
	*x = SERVICE_TYPE(value)
	return nil
}

func (SERVICE_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

type CONNECTION_STATUS_TYPE int32

const (
	CONNECTION_STATUS_TYPE_CONNECTED_WITHOUT_METER    CONNECTION_STATUS_TYPE = 0
	CONNECTION_STATUS_TYPE_CONNECTED_WITH_METER       CONNECTION_STATUS_TYPE = 1
	CONNECTION_STATUS_TYPE_DISCONNECTED_WITH_METER    CONNECTION_STATUS_TYPE = 2
	CONNECTION_STATUS_TYPE_DISCONNECTED_WITHOUT_METER CONNECTION_STATUS_TYPE = 3
)

var CONNECTION_STATUS_TYPE_name = map[int32]string{
	0: "CONNECTED_WITHOUT_METER",
	1: "CONNECTED_WITH_METER",
	2: "DISCONNECTED_WITH_METER",
	3: "DISCONNECTED_WITHOUT_METER",
}

var CONNECTION_STATUS_TYPE_value = map[string]int32{
	"CONNECTED_WITHOUT_METER":    0,
	"CONNECTED_WITH_METER":       1,
	"DISCONNECTED_WITH_METER":    2,
	"DISCONNECTED_WITHOUT_METER": 3,
}

func (x CONNECTION_STATUS_TYPE) Enum() *CONNECTION_STATUS_TYPE {
	p := new(CONNECTION_STATUS_TYPE)
	*p = x
	return p
}

func (x CONNECTION_STATUS_TYPE) String() string {
	return proto.EnumName(CONNECTION_STATUS_TYPE_name, int32(x))
}

func (x *CONNECTION_STATUS_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CONNECTION_STATUS_TYPE_value, data, "CONNECTION_STATUS_TYPE")
	if err != nil {
		return err
	}
	*x = CONNECTION_STATUS_TYPE(value)
	return nil
}

func (CONNECTION_STATUS_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

type READING_TYPE int32

const (
	READING_TYPE_ACTUAL   READING_TYPE = 0
	READING_TYPE_AVERAGE  READING_TYPE = 1
	READING_TYPE_ESTIMATE READING_TYPE = 2
)

var READING_TYPE_name = map[int32]string{
	0: "ACTUAL",
	1: "AVERAGE",
	2: "ESTIMATE",
}

var READING_TYPE_value = map[string]int32{
	"ACTUAL":   0,
	"AVERAGE":  1,
	"ESTIMATE": 2,
}

func (x READING_TYPE) Enum() *READING_TYPE {
	p := new(READING_TYPE)
	*p = x
	return p
}

func (x READING_TYPE) String() string {
	return proto.EnumName(READING_TYPE_name, int32(x))
}

func (x *READING_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(READING_TYPE_value, data, "READING_TYPE")
	if err != nil {
		return err
	}
	*x = READING_TYPE(value)
	return nil
}

func (READING_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{2}
}

type RegularChargePeriod int32

const (
	RegularChargePeriod_BILL    RegularChargePeriod = 1
	RegularChargePeriod_MONTHLY RegularChargePeriod = 2
)

var RegularChargePeriod_name = map[int32]string{
	1: "BILL",
	2: "MONTHLY",
}

var RegularChargePeriod_value = map[string]int32{
	"BILL":    1,
	"MONTHLY": 2,
}

func (x RegularChargePeriod) Enum() *RegularChargePeriod {
	p := new(RegularChargePeriod)
	*p = x
	return p
}

func (x RegularChargePeriod) String() string {
	return proto.EnumName(RegularChargePeriod_name, int32(x))
}

func (x *RegularChargePeriod) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RegularChargePeriod_value, data, "RegularChargePeriod")
	if err != nil {
		return err
	}
	*x = RegularChargePeriod(value)
	return nil
}

func (RegularChargePeriod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{3}
}

type ENTITY_TYPE int32

const (
	ENTITY_TYPE_CTG_TYPE                ENTITY_TYPE = 1
	ENTITY_TYPE_CUSTOMER_TYPE           ENTITY_TYPE = 2
	ENTITY_TYPE_CUSTOMER_FLAG1          ENTITY_TYPE = 3
	ENTITY_TYPE_CUSTOMER_FLAG2          ENTITY_TYPE = 4
	ENTITY_TYPE_CUSTOMER_FLAG3          ENTITY_TYPE = 5
	ENTITY_TYPE_CUSTOMER_FLAG4          ENTITY_TYPE = 6
	ENTITY_TYPE_CUSTOMER_FLAG5          ENTITY_TYPE = 7
	ENTITY_TYPE_PROPERTY_VACATED        ENTITY_TYPE = 8
	ENTITY_TYPE_PROPERTY_FLAG1          ENTITY_TYPE = 9
	ENTITY_TYPE_PROPERTY_FLAG2          ENTITY_TYPE = 10
	ENTITY_TYPE_PROPERTY_FLAG3          ENTITY_TYPE = 11
	ENTITY_TYPE_PROPERTY_FLAG4          ENTITY_TYPE = 12
	ENTITY_TYPE_PROPERTY_FLAG5          ENTITY_TYPE = 13
	ENTITY_TYPE_CONNECTION_DIAMETER     ENTITY_TYPE = 14
	ENTITY_TYPE_CONNECTION_STATUS       ENTITY_TYPE = 15
	ENTITY_TYPE_CONNECTION_ISBULK_METER ENTITY_TYPE = 16
	ENTITY_TYPE_METER_DIAMETER          ENTITY_TYPE = 17
	ENTITY_TYPE_SERVICE                 ENTITY_TYPE = 18
)

var ENTITY_TYPE_name = map[int32]string{
	1:  "CTG_TYPE",
	2:  "CUSTOMER_TYPE",
	3:  "CUSTOMER_FLAG1",
	4:  "CUSTOMER_FLAG2",
	5:  "CUSTOMER_FLAG3",
	6:  "CUSTOMER_FLAG4",
	7:  "CUSTOMER_FLAG5",
	8:  "PROPERTY_VACATED",
	9:  "PROPERTY_FLAG1",
	10: "PROPERTY_FLAG2",
	11: "PROPERTY_FLAG3",
	12: "PROPERTY_FLAG4",
	13: "PROPERTY_FLAG5",
	14: "CONNECTION_DIAMETER",
	15: "CONNECTION_STATUS",
	16: "CONNECTION_ISBULK_METER",
	17: "METER_DIAMETER",
	18: "SERVICE",
}

var ENTITY_TYPE_value = map[string]int32{
	"CTG_TYPE":                1,
	"CUSTOMER_TYPE":           2,
	"CUSTOMER_FLAG1":          3,
	"CUSTOMER_FLAG2":          4,
	"CUSTOMER_FLAG3":          5,
	"CUSTOMER_FLAG4":          6,
	"CUSTOMER_FLAG5":          7,
	"PROPERTY_VACATED":        8,
	"PROPERTY_FLAG1":          9,
	"PROPERTY_FLAG2":          10,
	"PROPERTY_FLAG3":          11,
	"PROPERTY_FLAG4":          12,
	"PROPERTY_FLAG5":          13,
	"CONNECTION_DIAMETER":     14,
	"CONNECTION_STATUS":       15,
	"CONNECTION_ISBULK_METER": 16,
	"METER_DIAMETER":          17,
	"SERVICE":                 18,
}

func (x ENTITY_TYPE) Enum() *ENTITY_TYPE {
	p := new(ENTITY_TYPE)
	*p = x
	return p
}

func (x ENTITY_TYPE) String() string {
	return proto.EnumName(ENTITY_TYPE_name, int32(x))
}

func (x *ENTITY_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ENTITY_TYPE_value, data, "ENTITY_TYPE")
	if err != nil {
		return err
	}
	*x = ENTITY_TYPE(value)
	return nil
}

func (ENTITY_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{4}
}

type ChargeRegularCalcBase int32

const (
	ChargeRegularCalcBase_MAIN_CONNECTION                 ChargeRegularCalcBase = 1
	ChargeRegularCalcBase_ALL_SUB_CONNECTION              ChargeRegularCalcBase = 2
	ChargeRegularCalcBase_HIEGH_PERCENTAGE_SUB_CONNECTION ChargeRegularCalcBase = 3
	ChargeRegularCalcBase_LOW_PERCENTAGE_CONNECTION       ChargeRegularCalcBase = 4
	ChargeRegularCalcBase_FIRST_SUB_CONNECTION            ChargeRegularCalcBase = 5
	ChargeRegularCalcBase_LAST_CONNECTION                 ChargeRegularCalcBase = 6
)

var ChargeRegularCalcBase_name = map[int32]string{
	1: "MAIN_CONNECTION",
	2: "ALL_SUB_CONNECTION",
	3: "HIEGH_PERCENTAGE_SUB_CONNECTION",
	4: "LOW_PERCENTAGE_CONNECTION",
	5: "FIRST_SUB_CONNECTION",
	6: "LAST_CONNECTION",
}

var ChargeRegularCalcBase_value = map[string]int32{
	"MAIN_CONNECTION":                 1,
	"ALL_SUB_CONNECTION":              2,
	"HIEGH_PERCENTAGE_SUB_CONNECTION": 3,
	"LOW_PERCENTAGE_CONNECTION":       4,
	"FIRST_SUB_CONNECTION":            5,
	"LAST_CONNECTION":                 6,
}

func (x ChargeRegularCalcBase) Enum() *ChargeRegularCalcBase {
	p := new(ChargeRegularCalcBase)
	*p = x
	return p
}

func (x ChargeRegularCalcBase) String() string {
	return proto.EnumName(ChargeRegularCalcBase_name, int32(x))
}

func (x *ChargeRegularCalcBase) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ChargeRegularCalcBase_value, data, "ChargeRegularCalcBase")
	if err != nil {
		return err
	}
	*x = ChargeRegularCalcBase(value)
	return nil
}

func (ChargeRegularCalcBase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{5}
}

//the entity meter used as entity type for calculation or enabling
//while the consump claculated
type Meter struct {
	MeterType            *string  `protobuf:"bytes,1,req,name=MeterType" json:"MeterType,omitempty"`
	MeterRef             *string  `protobuf:"bytes,2,req,name=MeterRef" json:"MeterRef,omitempty"`
	Diameter             *int64   `protobuf:"varint,3,req,name=Diameter" json:"Diameter,omitempty"`
	ConverterFactor      *int64   `protobuf:"varint,4,opt,name=ConverterFactor" json:"ConverterFactor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meter) Reset()         { *m = Meter{} }
func (m *Meter) String() string { return proto.CompactTextString(m) }
func (*Meter) ProtoMessage()    {}
func (*Meter) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *Meter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meter.Unmarshal(m, b)
}
func (m *Meter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meter.Marshal(b, m, deterministic)
}
func (m *Meter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meter.Merge(m, src)
}
func (m *Meter) XXX_Size() int {
	return xxx_messageInfo_Meter.Size(m)
}
func (m *Meter) XXX_DiscardUnknown() {
	xxx_messageInfo_Meter.DiscardUnknown(m)
}

var xxx_messageInfo_Meter proto.InternalMessageInfo

func (m *Meter) GetMeterType() string {
	if m != nil && m.MeterType != nil {
		return *m.MeterType
	}
	return ""
}

func (m *Meter) GetMeterRef() string {
	if m != nil && m.MeterRef != nil {
		return *m.MeterRef
	}
	return ""
}

func (m *Meter) GetDiameter() int64 {
	if m != nil && m.Diameter != nil {
		return *m.Diameter
	}
	return 0
}

func (m *Meter) GetConverterFactor() int64 {
	if m != nil && m.ConverterFactor != nil {
		return *m.ConverterFactor
	}
	return 0
}

type Connection struct {
	CType                *string                 `protobuf:"bytes,1,req,name=CType" json:"CType,omitempty"`
	NoUnits              *int64                  `protobuf:"varint,2,req,name=NoUnits" json:"NoUnits,omitempty"`
	IsBulkMeter          *bool                   `protobuf:"varint,3,opt,name=IsBulkMeter" json:"IsBulkMeter,omitempty"`
	ConnDiameter         *int64                  `protobuf:"varint,4,opt,name=ConnDiameter" json:"ConnDiameter,omitempty"`
	Meter                *Meter                  `protobuf:"bytes,5,opt,name=Meter" json:"Meter,omitempty"`
	EstimCons            *float64                `protobuf:"fixed64,6,opt,name=EstimCons" json:"EstimCons,omitempty"`
	ConnectionStatus     *CONNECTION_STATUS_TYPE `protobuf:"varint,7,opt,name=ConnectionStatus,enum=billing.CONNECTION_STATUS_TYPE" json:"ConnectionStatus,omitempty"`
	SubConnections       []*SubConnection        `protobuf:"bytes,8,rep,name=SubConnections" json:"SubConnections,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}
func (*Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

func (m *Connection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connection.Unmarshal(m, b)
}
func (m *Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connection.Marshal(b, m, deterministic)
}
func (m *Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connection.Merge(m, src)
}
func (m *Connection) XXX_Size() int {
	return xxx_messageInfo_Connection.Size(m)
}
func (m *Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_Connection proto.InternalMessageInfo

func (m *Connection) GetCType() string {
	if m != nil && m.CType != nil {
		return *m.CType
	}
	return ""
}

func (m *Connection) GetNoUnits() int64 {
	if m != nil && m.NoUnits != nil {
		return *m.NoUnits
	}
	return 0
}

func (m *Connection) GetIsBulkMeter() bool {
	if m != nil && m.IsBulkMeter != nil {
		return *m.IsBulkMeter
	}
	return false
}

func (m *Connection) GetConnDiameter() int64 {
	if m != nil && m.ConnDiameter != nil {
		return *m.ConnDiameter
	}
	return 0
}

func (m *Connection) GetMeter() *Meter {
	if m != nil {
		return m.Meter
	}
	return nil
}

func (m *Connection) GetEstimCons() float64 {
	if m != nil && m.EstimCons != nil {
		return *m.EstimCons
	}
	return 0
}

func (m *Connection) GetConnectionStatus() CONNECTION_STATUS_TYPE {
	if m != nil && m.ConnectionStatus != nil {
		return *m.ConnectionStatus
	}
	return CONNECTION_STATUS_TYPE_CONNECTED_WITHOUT_METER
}

func (m *Connection) GetSubConnections() []*SubConnection {
	if m != nil {
		return m.SubConnections
	}
	return nil
}

type SubConnection struct {
	CType                      *string  `protobuf:"bytes,1,req,name=CType" json:"CType,omitempty"`
	EstimateConsumptionPerUnit *float64 `protobuf:"fixed64,2,opt,name=EstimateConsumptionPerUnit" json:"EstimateConsumptionPerUnit,omitempty"`
	ConsumptionPercentage      *float64 `protobuf:"fixed64,3,opt,name=ConsumptionPercentage" json:"ConsumptionPercentage,omitempty"`
	NoUnits                    *int64   `protobuf:"varint,4,opt,name=NoUnits" json:"NoUnits,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *SubConnection) Reset()         { *m = SubConnection{} }
func (m *SubConnection) String() string { return proto.CompactTextString(m) }
func (*SubConnection) ProtoMessage()    {}
func (*SubConnection) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{2}
}

func (m *SubConnection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubConnection.Unmarshal(m, b)
}
func (m *SubConnection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubConnection.Marshal(b, m, deterministic)
}
func (m *SubConnection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubConnection.Merge(m, src)
}
func (m *SubConnection) XXX_Size() int {
	return xxx_messageInfo_SubConnection.Size(m)
}
func (m *SubConnection) XXX_DiscardUnknown() {
	xxx_messageInfo_SubConnection.DiscardUnknown(m)
}

var xxx_messageInfo_SubConnection proto.InternalMessageInfo

func (m *SubConnection) GetCType() string {
	if m != nil && m.CType != nil {
		return *m.CType
	}
	return ""
}

func (m *SubConnection) GetEstimateConsumptionPerUnit() float64 {
	if m != nil && m.EstimateConsumptionPerUnit != nil {
		return *m.EstimateConsumptionPerUnit
	}
	return 0
}

func (m *SubConnection) GetConsumptionPercentage() float64 {
	if m != nil && m.ConsumptionPercentage != nil {
		return *m.ConsumptionPercentage
	}
	return 0
}

func (m *SubConnection) GetNoUnits() int64 {
	if m != nil && m.NoUnits != nil {
		return *m.NoUnits
	}
	return 0
}

type Service struct {
	ServiceType          *SERVICE_TYPE `protobuf:"varint,1,req,name=ServiceType,enum=billing.SERVICE_TYPE" json:"ServiceType,omitempty"`
	Connection           *Connection   `protobuf:"bytes,2,req,name=Connection" json:"Connection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{3}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetServiceType() SERVICE_TYPE {
	if m != nil && m.ServiceType != nil {
		return *m.ServiceType
	}
	return SERVICE_TYPE_WATER
}

func (m *Service) GetConnection() *Connection {
	if m != nil {
		return m.Connection
	}
	return nil
}

type Property struct {
	PropRef              *string    `protobuf:"bytes,1,req,name=PropRef" json:"PropRef,omitempty"`
	InfoFlag1            *string    `protobuf:"bytes,3,opt,name=InfoFlag1" json:"InfoFlag1,omitempty"`
	InfoFlag2            *string    `protobuf:"bytes,4,opt,name=InfoFlag2" json:"InfoFlag2,omitempty"`
	InfoFlag3            *string    `protobuf:"bytes,5,opt,name=InfoFlag3" json:"InfoFlag3,omitempty"`
	InfoFlag4            *string    `protobuf:"bytes,6,opt,name=InfoFlag4" json:"InfoFlag4,omitempty"`
	InfoFlag5            *string    `protobuf:"bytes,7,opt,name=InfoFlag5" json:"InfoFlag5,omitempty"`
	NoRooms              *int64     `protobuf:"varint,8,opt,name=NoRooms" json:"NoRooms,omitempty"`
	Services             []*Service `protobuf:"bytes,9,rep,name=Services" json:"Services,omitempty"`
	IsVacated            *bool      `protobuf:"varint,10,opt,name=IsVacated" json:"IsVacated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Property) Reset()         { *m = Property{} }
func (m *Property) String() string { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()    {}
func (*Property) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{4}
}

func (m *Property) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Property.Unmarshal(m, b)
}
func (m *Property) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Property.Marshal(b, m, deterministic)
}
func (m *Property) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Property.Merge(m, src)
}
func (m *Property) XXX_Size() int {
	return xxx_messageInfo_Property.Size(m)
}
func (m *Property) XXX_DiscardUnknown() {
	xxx_messageInfo_Property.DiscardUnknown(m)
}

var xxx_messageInfo_Property proto.InternalMessageInfo

func (m *Property) GetPropRef() string {
	if m != nil && m.PropRef != nil {
		return *m.PropRef
	}
	return ""
}

func (m *Property) GetInfoFlag1() string {
	if m != nil && m.InfoFlag1 != nil {
		return *m.InfoFlag1
	}
	return ""
}

func (m *Property) GetInfoFlag2() string {
	if m != nil && m.InfoFlag2 != nil {
		return *m.InfoFlag2
	}
	return ""
}

func (m *Property) GetInfoFlag3() string {
	if m != nil && m.InfoFlag3 != nil {
		return *m.InfoFlag3
	}
	return ""
}

func (m *Property) GetInfoFlag4() string {
	if m != nil && m.InfoFlag4 != nil {
		return *m.InfoFlag4
	}
	return ""
}

func (m *Property) GetInfoFlag5() string {
	if m != nil && m.InfoFlag5 != nil {
		return *m.InfoFlag5
	}
	return ""
}

func (m *Property) GetNoRooms() int64 {
	if m != nil && m.NoRooms != nil {
		return *m.NoRooms
	}
	return 0
}

func (m *Property) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *Property) GetIsVacated() bool {
	if m != nil && m.IsVacated != nil {
		return *m.IsVacated
	}
	return false
}

type Customer struct {
	Custkey              *string   `protobuf:"bytes,1,req,name=Custkey" json:"Custkey,omitempty"`
	CustType             *int64    `protobuf:"varint,2,req,name=CustType" json:"CustType,omitempty"`
	IsCompany            *bool     `protobuf:"varint,3,opt,name=IsCompany" json:"IsCompany,omitempty"`
	InfoFlag1            *string   `protobuf:"bytes,4,opt,name=InfoFlag1" json:"InfoFlag1,omitempty"`
	InfoFlag2            *string   `protobuf:"bytes,5,opt,name=InfoFlag2" json:"InfoFlag2,omitempty"`
	InfoFlag3            *string   `protobuf:"bytes,6,opt,name=InfoFlag3" json:"InfoFlag3,omitempty"`
	InfoFlag4            *string   `protobuf:"bytes,7,opt,name=InfoFlag4" json:"InfoFlag4,omitempty"`
	InfoFlag5            *string   `protobuf:"bytes,8,opt,name=InfoFlag5" json:"InfoFlag5,omitempty"`
	Property             *Property `protobuf:"bytes,9,opt,name=Property" json:"Property,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{5}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetCustkey() string {
	if m != nil && m.Custkey != nil {
		return *m.Custkey
	}
	return ""
}

func (m *Customer) GetCustType() int64 {
	if m != nil && m.CustType != nil {
		return *m.CustType
	}
	return 0
}

func (m *Customer) GetIsCompany() bool {
	if m != nil && m.IsCompany != nil {
		return *m.IsCompany
	}
	return false
}

func (m *Customer) GetInfoFlag1() string {
	if m != nil && m.InfoFlag1 != nil {
		return *m.InfoFlag1
	}
	return ""
}

func (m *Customer) GetInfoFlag2() string {
	if m != nil && m.InfoFlag2 != nil {
		return *m.InfoFlag2
	}
	return ""
}

func (m *Customer) GetInfoFlag3() string {
	if m != nil && m.InfoFlag3 != nil {
		return *m.InfoFlag3
	}
	return ""
}

func (m *Customer) GetInfoFlag4() string {
	if m != nil && m.InfoFlag4 != nil {
		return *m.InfoFlag4
	}
	return ""
}

func (m *Customer) GetInfoFlag5() string {
	if m != nil && m.InfoFlag5 != nil {
		return *m.InfoFlag5
	}
	return ""
}

func (m *Customer) GetProperty() *Property {
	if m != nil {
		return m.Property
	}
	return nil
}

//is overall all actual or estim consumption for each service
type Reading struct {
	Consump              *float64             `protobuf:"fixed64,1,req,name=Consump" json:"Consump,omitempty"`
	ReadingType          *READING_TYPE        `protobuf:"varint,2,req,name=ReadingType,enum=billing.READING_TYPE" json:"ReadingType,omitempty"`
	PrReading            *float64             `protobuf:"fixed64,3,opt,name=PrReading" json:"PrReading,omitempty"`
	CrReading            *float64             `protobuf:"fixed64,4,opt,name=CrReading" json:"CrReading,omitempty"`
	PR_DATE              *timestamp.Timestamp `protobuf:"bytes,5,opt,name=PR_DATE,json=PRDATE" json:"PR_DATE,omitempty"`
	CR_DATE              *timestamp.Timestamp `protobuf:"bytes,6,opt,name=CR_DATE,json=CRDATE" json:"CR_DATE,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Reading) Reset()         { *m = Reading{} }
func (m *Reading) String() string { return proto.CompactTextString(m) }
func (*Reading) ProtoMessage()    {}
func (*Reading) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{6}
}

func (m *Reading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reading.Unmarshal(m, b)
}
func (m *Reading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reading.Marshal(b, m, deterministic)
}
func (m *Reading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reading.Merge(m, src)
}
func (m *Reading) XXX_Size() int {
	return xxx_messageInfo_Reading.Size(m)
}
func (m *Reading) XXX_DiscardUnknown() {
	xxx_messageInfo_Reading.DiscardUnknown(m)
}

var xxx_messageInfo_Reading proto.InternalMessageInfo

func (m *Reading) GetConsump() float64 {
	if m != nil && m.Consump != nil {
		return *m.Consump
	}
	return 0
}

func (m *Reading) GetReadingType() READING_TYPE {
	if m != nil && m.ReadingType != nil {
		return *m.ReadingType
	}
	return READING_TYPE_ACTUAL
}

func (m *Reading) GetPrReading() float64 {
	if m != nil && m.PrReading != nil {
		return *m.PrReading
	}
	return 0
}

func (m *Reading) GetCrReading() float64 {
	if m != nil && m.CrReading != nil {
		return *m.CrReading
	}
	return 0
}

func (m *Reading) GetPR_DATE() *timestamp.Timestamp {
	if m != nil {
		return m.PR_DATE
	}
	return nil
}

func (m *Reading) GetCR_DATE() *timestamp.Timestamp {
	if m != nil {
		return m.CR_DATE
	}
	return nil
}

//each service may be has its meter (server meters,fire meters,electrcity meters)
type ServiceReading struct {
	ServiceType          *SERVICE_TYPE `protobuf:"varint,1,req,name=ServiceType,enum=billing.SERVICE_TYPE" json:"ServiceType,omitempty"`
	Reading              *Reading      `protobuf:"bytes,2,req,name=Reading" json:"Reading,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ServiceReading) Reset()         { *m = ServiceReading{} }
func (m *ServiceReading) String() string { return proto.CompactTextString(m) }
func (*ServiceReading) ProtoMessage()    {}
func (*ServiceReading) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{7}
}

func (m *ServiceReading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceReading.Unmarshal(m, b)
}
func (m *ServiceReading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceReading.Marshal(b, m, deterministic)
}
func (m *ServiceReading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceReading.Merge(m, src)
}
func (m *ServiceReading) XXX_Size() int {
	return xxx_messageInfo_ServiceReading.Size(m)
}
func (m *ServiceReading) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceReading.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceReading proto.InternalMessageInfo

func (m *ServiceReading) GetServiceType() SERVICE_TYPE {
	if m != nil && m.ServiceType != nil {
		return *m.ServiceType
	}
	return SERVICE_TYPE_WATER
}

func (m *ServiceReading) GetReading() *Reading {
	if m != nil {
		return m.Reading
	}
	return nil
}

// each billing request should have the customer entity and the reading for each service
type BillRequest struct {
	Customer             *Customer         `protobuf:"bytes,1,req,name=Customer" json:"Customer,omitempty"`
	ServicesReadings     []*ServiceReading `protobuf:"bytes,2,rep,name=ServicesReadings" json:"ServicesReadings,omitempty"`
	IgnoreTimeEffect     *bool             `protobuf:"varint,3,req,name=IgnoreTimeEffect" json:"IgnoreTimeEffect,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BillRequest) Reset()         { *m = BillRequest{} }
func (m *BillRequest) String() string { return proto.CompactTextString(m) }
func (*BillRequest) ProtoMessage()    {}
func (*BillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{8}
}

func (m *BillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BillRequest.Unmarshal(m, b)
}
func (m *BillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BillRequest.Marshal(b, m, deterministic)
}
func (m *BillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BillRequest.Merge(m, src)
}
func (m *BillRequest) XXX_Size() int {
	return xxx_messageInfo_BillRequest.Size(m)
}
func (m *BillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BillRequest proto.InternalMessageInfo

func (m *BillRequest) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *BillRequest) GetServicesReadings() []*ServiceReading {
	if m != nil {
		return m.ServicesReadings
	}
	return nil
}

func (m *BillRequest) GetIgnoreTimeEffect() bool {
	if m != nil && m.IgnoreTimeEffect != nil {
		return *m.IgnoreTimeEffect
	}
	return false
}

//the expected responce is the amount for each service
type ExtraCharge struct {
	DESCRIPTION          *string  `protobuf:"bytes,1,opt,name=DESCRIPTION" json:"DESCRIPTION,omitempty"`
	Code                 *string  `protobuf:"bytes,2,req,name=Code" json:"Code,omitempty"`
	Amount               *float64 `protobuf:"fixed64,3,req,name=Amount" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtraCharge) Reset()         { *m = ExtraCharge{} }
func (m *ExtraCharge) String() string { return proto.CompactTextString(m) }
func (*ExtraCharge) ProtoMessage()    {}
func (*ExtraCharge) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{9}
}

func (m *ExtraCharge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtraCharge.Unmarshal(m, b)
}
func (m *ExtraCharge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtraCharge.Marshal(b, m, deterministic)
}
func (m *ExtraCharge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtraCharge.Merge(m, src)
}
func (m *ExtraCharge) XXX_Size() int {
	return xxx_messageInfo_ExtraCharge.Size(m)
}
func (m *ExtraCharge) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtraCharge.DiscardUnknown(m)
}

var xxx_messageInfo_ExtraCharge proto.InternalMessageInfo

func (m *ExtraCharge) GetDESCRIPTION() string {
	if m != nil && m.DESCRIPTION != nil {
		return *m.DESCRIPTION
	}
	return ""
}

func (m *ExtraCharge) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *ExtraCharge) GetAmount() float64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

type BillResponceItemCtg struct {
	CType                *float64 `protobuf:"fixed64,1,req,name=CType" json:"CType,omitempty"`
	Amount               *float64 `protobuf:"fixed64,2,req,name=Amount" json:"Amount,omitempty"`
	TaxAmount            *float64 `protobuf:"fixed64,3,opt,name=TaxAmount" json:"TaxAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BillResponceItemCtg) Reset()         { *m = BillResponceItemCtg{} }
func (m *BillResponceItemCtg) String() string { return proto.CompactTextString(m) }
func (*BillResponceItemCtg) ProtoMessage()    {}
func (*BillResponceItemCtg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{10}
}

func (m *BillResponceItemCtg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BillResponceItemCtg.Unmarshal(m, b)
}
func (m *BillResponceItemCtg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BillResponceItemCtg.Marshal(b, m, deterministic)
}
func (m *BillResponceItemCtg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BillResponceItemCtg.Merge(m, src)
}
func (m *BillResponceItemCtg) XXX_Size() int {
	return xxx_messageInfo_BillResponceItemCtg.Size(m)
}
func (m *BillResponceItemCtg) XXX_DiscardUnknown() {
	xxx_messageInfo_BillResponceItemCtg.DiscardUnknown(m)
}

var xxx_messageInfo_BillResponceItemCtg proto.InternalMessageInfo

func (m *BillResponceItemCtg) GetCType() float64 {
	if m != nil && m.CType != nil {
		return *m.CType
	}
	return 0
}

func (m *BillResponceItemCtg) GetAmount() float64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *BillResponceItemCtg) GetTaxAmount() float64 {
	if m != nil && m.TaxAmount != nil {
		return *m.TaxAmount
	}
	return 0
}

type BillResponceItem struct {
	ServiceType          *SERVICE_TYPE          `protobuf:"varint,1,req,name=ServiceType,enum=billing.SERVICE_TYPE" json:"ServiceType,omitempty"`
	Charges              []*BillResponceItemCtg `protobuf:"bytes,2,rep,name=Charges" json:"Charges,omitempty"`
	ExtraCharges         []*ExtraCharge         `protobuf:"bytes,99,rep,name=ExtraCharges" json:"ExtraCharges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BillResponceItem) Reset()         { *m = BillResponceItem{} }
func (m *BillResponceItem) String() string { return proto.CompactTextString(m) }
func (*BillResponceItem) ProtoMessage()    {}
func (*BillResponceItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{11}
}

func (m *BillResponceItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BillResponceItem.Unmarshal(m, b)
}
func (m *BillResponceItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BillResponceItem.Marshal(b, m, deterministic)
}
func (m *BillResponceItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BillResponceItem.Merge(m, src)
}
func (m *BillResponceItem) XXX_Size() int {
	return xxx_messageInfo_BillResponceItem.Size(m)
}
func (m *BillResponceItem) XXX_DiscardUnknown() {
	xxx_messageInfo_BillResponceItem.DiscardUnknown(m)
}

var xxx_messageInfo_BillResponceItem proto.InternalMessageInfo

func (m *BillResponceItem) GetServiceType() SERVICE_TYPE {
	if m != nil && m.ServiceType != nil {
		return *m.ServiceType
	}
	return SERVICE_TYPE_WATER
}

func (m *BillResponceItem) GetCharges() []*BillResponceItemCtg {
	if m != nil {
		return m.Charges
	}
	return nil
}

func (m *BillResponceItem) GetExtraCharges() []*ExtraCharge {
	if m != nil {
		return m.ExtraCharges
	}
	return nil
}

type BillResponce struct {
	Charges              []*BillResponceItem `protobuf:"bytes,1,rep,name=Charges" json:"Charges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BillResponce) Reset()         { *m = BillResponce{} }
func (m *BillResponce) String() string { return proto.CompactTextString(m) }
func (*BillResponce) ProtoMessage()    {}
func (*BillResponce) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{12}
}

func (m *BillResponce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BillResponce.Unmarshal(m, b)
}
func (m *BillResponce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BillResponce.Marshal(b, m, deterministic)
}
func (m *BillResponce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BillResponce.Merge(m, src)
}
func (m *BillResponce) XXX_Size() int {
	return xxx_messageInfo_BillResponce.Size(m)
}
func (m *BillResponce) XXX_DiscardUnknown() {
	xxx_messageInfo_BillResponce.DiscardUnknown(m)
}

var xxx_messageInfo_BillResponce proto.InternalMessageInfo

func (m *BillResponce) GetCharges() []*BillResponceItem {
	if m != nil {
		return m.Charges
	}
	return nil
}

type ServiceTariff struct {
	ServiceType          *SERVICE_TYPE `protobuf:"varint,1,req,name=ServiceType,enum=billing.SERVICE_TYPE" json:"ServiceType,omitempty"`
	TarifId              *string       `protobuf:"bytes,2,req,name=TarifId" json:"TarifId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ServiceTariff) Reset()         { *m = ServiceTariff{} }
func (m *ServiceTariff) String() string { return proto.CompactTextString(m) }
func (*ServiceTariff) ProtoMessage()    {}
func (*ServiceTariff) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{13}
}

func (m *ServiceTariff) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceTariff.Unmarshal(m, b)
}
func (m *ServiceTariff) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceTariff.Marshal(b, m, deterministic)
}
func (m *ServiceTariff) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceTariff.Merge(m, src)
}
func (m *ServiceTariff) XXX_Size() int {
	return xxx_messageInfo_ServiceTariff.Size(m)
}
func (m *ServiceTariff) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceTariff.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceTariff proto.InternalMessageInfo

func (m *ServiceTariff) GetServiceType() SERVICE_TYPE {
	if m != nil && m.ServiceType != nil {
		return *m.ServiceType
	}
	return SERVICE_TYPE_WATER
}

func (m *ServiceTariff) GetTarifId() string {
	if m != nil && m.TarifId != nil {
		return *m.TarifId
	}
	return ""
}

type Ctg struct {
	CType                *string          `protobuf:"bytes,1,req,name=CType" json:"CType,omitempty"`
	Tariffs              []*ServiceTariff `protobuf:"bytes,2,rep,name=Tariffs" json:"Tariffs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Ctg) Reset()         { *m = Ctg{} }
func (m *Ctg) String() string { return proto.CompactTextString(m) }
func (*Ctg) ProtoMessage()    {}
func (*Ctg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{14}
}

func (m *Ctg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ctg.Unmarshal(m, b)
}
func (m *Ctg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ctg.Marshal(b, m, deterministic)
}
func (m *Ctg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ctg.Merge(m, src)
}
func (m *Ctg) XXX_Size() int {
	return xxx_messageInfo_Ctg.Size(m)
}
func (m *Ctg) XXX_DiscardUnknown() {
	xxx_messageInfo_Ctg.DiscardUnknown(m)
}

var xxx_messageInfo_Ctg proto.InternalMessageInfo

func (m *Ctg) GetCType() string {
	if m != nil && m.CType != nil {
		return *m.CType
	}
	return ""
}

func (m *Ctg) GetTariffs() []*ServiceTariff {
	if m != nil {
		return m.Tariffs
	}
	return nil
}

type CtgRequest struct {
	Ctgs                 []*Ctg   `protobuf:"bytes,2,rep,name=Ctgs" json:"Ctgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CtgRequest) Reset()         { *m = CtgRequest{} }
func (m *CtgRequest) String() string { return proto.CompactTextString(m) }
func (*CtgRequest) ProtoMessage()    {}
func (*CtgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{15}
}

func (m *CtgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CtgRequest.Unmarshal(m, b)
}
func (m *CtgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CtgRequest.Marshal(b, m, deterministic)
}
func (m *CtgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CtgRequest.Merge(m, src)
}
func (m *CtgRequest) XXX_Size() int {
	return xxx_messageInfo_CtgRequest.Size(m)
}
func (m *CtgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CtgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CtgRequest proto.InternalMessageInfo

func (m *CtgRequest) GetCtgs() []*Ctg {
	if m != nil {
		return m.Ctgs
	}
	return nil
}

type ExtraTariffFess struct {
	Code                 *string  `protobuf:"bytes,1,req,name=Code" json:"Code,omitempty"`
	Description          *string  `protobuf:"bytes,2,opt,name=Description" json:"Description,omitempty"`
	AmountPerMeter       *float64 `protobuf:"fixed64,3,opt,name=AmountPerMeter" json:"AmountPerMeter,omitempty"`
	AmountPercentage     *float64 `protobuf:"fixed64,4,opt,name=AmountPercentage" json:"AmountPercentage,omitempty"`
	FixedAmount          *float64 `protobuf:"fixed64,5,opt,name=FixedAmount" json:"FixedAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtraTariffFess) Reset()         { *m = ExtraTariffFess{} }
func (m *ExtraTariffFess) String() string { return proto.CompactTextString(m) }
func (*ExtraTariffFess) ProtoMessage()    {}
func (*ExtraTariffFess) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{16}
}

func (m *ExtraTariffFess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtraTariffFess.Unmarshal(m, b)
}
func (m *ExtraTariffFess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtraTariffFess.Marshal(b, m, deterministic)
}
func (m *ExtraTariffFess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtraTariffFess.Merge(m, src)
}
func (m *ExtraTariffFess) XXX_Size() int {
	return xxx_messageInfo_ExtraTariffFess.Size(m)
}
func (m *ExtraTariffFess) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtraTariffFess.DiscardUnknown(m)
}

var xxx_messageInfo_ExtraTariffFess proto.InternalMessageInfo

func (m *ExtraTariffFess) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *ExtraTariffFess) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *ExtraTariffFess) GetAmountPerMeter() float64 {
	if m != nil && m.AmountPerMeter != nil {
		return *m.AmountPerMeter
	}
	return 0
}

func (m *ExtraTariffFess) GetAmountPercentage() float64 {
	if m != nil && m.AmountPercentage != nil {
		return *m.AmountPercentage
	}
	return 0
}

func (m *ExtraTariffFess) GetFixedAmount() float64 {
	if m != nil && m.FixedAmount != nil {
		return *m.FixedAmount
	}
	return 0
}

type TariffBand struct {
	From                 *float64 `protobuf:"fixed64,1,req,name=From" json:"From,omitempty"`
	To                   *float64 `protobuf:"fixed64,2,req,name=To" json:"To,omitempty"`
	Constant             *float64 `protobuf:"fixed64,3,req,name=Constant" json:"Constant,omitempty"`
	Factor               *float64 `protobuf:"fixed64,4,req,name=Factor" json:"Factor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TariffBand) Reset()         { *m = TariffBand{} }
func (m *TariffBand) String() string { return proto.CompactTextString(m) }
func (*TariffBand) ProtoMessage()    {}
func (*TariffBand) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{17}
}

func (m *TariffBand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TariffBand.Unmarshal(m, b)
}
func (m *TariffBand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TariffBand.Marshal(b, m, deterministic)
}
func (m *TariffBand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TariffBand.Merge(m, src)
}
func (m *TariffBand) XXX_Size() int {
	return xxx_messageInfo_TariffBand.Size(m)
}
func (m *TariffBand) XXX_DiscardUnknown() {
	xxx_messageInfo_TariffBand.DiscardUnknown(m)
}

var xxx_messageInfo_TariffBand proto.InternalMessageInfo

func (m *TariffBand) GetFrom() float64 {
	if m != nil && m.From != nil {
		return *m.From
	}
	return 0
}

func (m *TariffBand) GetTo() float64 {
	if m != nil && m.To != nil {
		return *m.To
	}
	return 0
}

func (m *TariffBand) GetConstant() float64 {
	if m != nil && m.Constant != nil {
		return *m.Constant
	}
	return 0
}

func (m *TariffBand) GetFactor() float64 {
	if m != nil && m.Factor != nil {
		return *m.Factor
	}
	return 0
}

type Tariff struct {
	TariffId             *string            `protobuf:"bytes,1,req,name=TariffId" json:"TariffId,omitempty"`
	TaxPercentage        *float64           `protobuf:"fixed64,2,opt,name=TaxPercentage" json:"TaxPercentage,omitempty"`
	DiscountPercentage   *float64           `protobuf:"fixed64,3,opt,name=DiscountPercentage" json:"DiscountPercentage,omitempty"`
	ExtraFees            []*ExtraTariffFess `protobuf:"bytes,4,rep,name=ExtraFees" json:"ExtraFees,omitempty"`
	Bands                []*TariffBand      `protobuf:"bytes,5,rep,name=Bands" json:"Bands,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Tariff) Reset()         { *m = Tariff{} }
func (m *Tariff) String() string { return proto.CompactTextString(m) }
func (*Tariff) ProtoMessage()    {}
func (*Tariff) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{18}
}

func (m *Tariff) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tariff.Unmarshal(m, b)
}
func (m *Tariff) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tariff.Marshal(b, m, deterministic)
}
func (m *Tariff) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tariff.Merge(m, src)
}
func (m *Tariff) XXX_Size() int {
	return xxx_messageInfo_Tariff.Size(m)
}
func (m *Tariff) XXX_DiscardUnknown() {
	xxx_messageInfo_Tariff.DiscardUnknown(m)
}

var xxx_messageInfo_Tariff proto.InternalMessageInfo

func (m *Tariff) GetTariffId() string {
	if m != nil && m.TariffId != nil {
		return *m.TariffId
	}
	return ""
}

func (m *Tariff) GetTaxPercentage() float64 {
	if m != nil && m.TaxPercentage != nil {
		return *m.TaxPercentage
	}
	return 0
}

func (m *Tariff) GetDiscountPercentage() float64 {
	if m != nil && m.DiscountPercentage != nil {
		return *m.DiscountPercentage
	}
	return 0
}

func (m *Tariff) GetExtraFees() []*ExtraTariffFess {
	if m != nil {
		return m.ExtraFees
	}
	return nil
}

func (m *Tariff) GetBands() []*TariffBand {
	if m != nil {
		return m.Bands
	}
	return nil
}

type TariffRequest struct {
	Tariffs              []*Tariff `protobuf:"bytes,1,rep,name=Tariffs" json:"Tariffs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TariffRequest) Reset()         { *m = TariffRequest{} }
func (m *TariffRequest) String() string { return proto.CompactTextString(m) }
func (*TariffRequest) ProtoMessage()    {}
func (*TariffRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{19}
}

func (m *TariffRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TariffRequest.Unmarshal(m, b)
}
func (m *TariffRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TariffRequest.Marshal(b, m, deterministic)
}
func (m *TariffRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TariffRequest.Merge(m, src)
}
func (m *TariffRequest) XXX_Size() int {
	return xxx_messageInfo_TariffRequest.Size(m)
}
func (m *TariffRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TariffRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TariffRequest proto.InternalMessageInfo

func (m *TariffRequest) GetTariffs() []*Tariff {
	if m != nil {
		return m.Tariffs
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{20}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type EntityChargeMappedValue struct {
	From                 *float64 `protobuf:"fixed64,1,opt,name=From" json:"From,omitempty"`
	To                   *float64 `protobuf:"fixed64,2,opt,name=To" json:"To,omitempty"`
	LuKey                *string  `protobuf:"bytes,3,opt,name=LuKey" json:"LuKey,omitempty"`
	Value                *float64 `protobuf:"fixed64,4,opt,name=Value" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityChargeMappedValue) Reset()         { *m = EntityChargeMappedValue{} }
func (m *EntityChargeMappedValue) String() string { return proto.CompactTextString(m) }
func (*EntityChargeMappedValue) ProtoMessage()    {}
func (*EntityChargeMappedValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{21}
}

func (m *EntityChargeMappedValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityChargeMappedValue.Unmarshal(m, b)
}
func (m *EntityChargeMappedValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityChargeMappedValue.Marshal(b, m, deterministic)
}
func (m *EntityChargeMappedValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityChargeMappedValue.Merge(m, src)
}
func (m *EntityChargeMappedValue) XXX_Size() int {
	return xxx_messageInfo_EntityChargeMappedValue.Size(m)
}
func (m *EntityChargeMappedValue) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityChargeMappedValue.DiscardUnknown(m)
}

var xxx_messageInfo_EntityChargeMappedValue proto.InternalMessageInfo

func (m *EntityChargeMappedValue) GetFrom() float64 {
	if m != nil && m.From != nil {
		return *m.From
	}
	return 0
}

func (m *EntityChargeMappedValue) GetTo() float64 {
	if m != nil && m.To != nil {
		return *m.To
	}
	return 0
}

func (m *EntityChargeMappedValue) GetLuKey() string {
	if m != nil && m.LuKey != nil {
		return *m.LuKey
	}
	return ""
}

func (m *EntityChargeMappedValue) GetValue() float64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type EntityEnableMappedValue struct {
	LuKey                *string  `protobuf:"bytes,3,req,name=LuKey" json:"LuKey,omitempty"`
	Value                *bool    `protobuf:"varint,4,opt,name=Value" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityEnableMappedValue) Reset()         { *m = EntityEnableMappedValue{} }
func (m *EntityEnableMappedValue) String() string { return proto.CompactTextString(m) }
func (*EntityEnableMappedValue) ProtoMessage()    {}
func (*EntityEnableMappedValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{22}
}

func (m *EntityEnableMappedValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityEnableMappedValue.Unmarshal(m, b)
}
func (m *EntityEnableMappedValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityEnableMappedValue.Marshal(b, m, deterministic)
}
func (m *EntityEnableMappedValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityEnableMappedValue.Merge(m, src)
}
func (m *EntityEnableMappedValue) XXX_Size() int {
	return xxx_messageInfo_EntityEnableMappedValue.Size(m)
}
func (m *EntityEnableMappedValue) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityEnableMappedValue.DiscardUnknown(m)
}

var xxx_messageInfo_EntityEnableMappedValue proto.InternalMessageInfo

func (m *EntityEnableMappedValue) GetLuKey() string {
	if m != nil && m.LuKey != nil {
		return *m.LuKey
	}
	return ""
}

func (m *EntityEnableMappedValue) GetValue() bool {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return false
}

type RegularChargeEntity struct {
	Code       *string      `protobuf:"bytes,1,req,name=Code" json:"Code,omitempty"`
	EntityType *ENTITY_TYPE `protobuf:"varint,2,req,name=EntityType,enum=billing.ENTITY_TYPE" json:"EntityType,omitempty"`
	//required string EntityField=3;
	PerUnit              *bool                      `protobuf:"varint,4,opt,name=PerUnit" json:"PerUnit,omitempty"`
	Fixed                *bool                      `protobuf:"varint,5,opt,name=Fixed" json:"Fixed,omitempty"`
	MappedValues         []*EntityChargeMappedValue `protobuf:"bytes,6,rep,name=MappedValues" json:"MappedValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RegularChargeEntity) Reset()         { *m = RegularChargeEntity{} }
func (m *RegularChargeEntity) String() string { return proto.CompactTextString(m) }
func (*RegularChargeEntity) ProtoMessage()    {}
func (*RegularChargeEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{23}
}

func (m *RegularChargeEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegularChargeEntity.Unmarshal(m, b)
}
func (m *RegularChargeEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegularChargeEntity.Marshal(b, m, deterministic)
}
func (m *RegularChargeEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegularChargeEntity.Merge(m, src)
}
func (m *RegularChargeEntity) XXX_Size() int {
	return xxx_messageInfo_RegularChargeEntity.Size(m)
}
func (m *RegularChargeEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_RegularChargeEntity.DiscardUnknown(m)
}

var xxx_messageInfo_RegularChargeEntity proto.InternalMessageInfo

func (m *RegularChargeEntity) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *RegularChargeEntity) GetEntityType() ENTITY_TYPE {
	if m != nil && m.EntityType != nil {
		return *m.EntityType
	}
	return ENTITY_TYPE_CTG_TYPE
}

func (m *RegularChargeEntity) GetPerUnit() bool {
	if m != nil && m.PerUnit != nil {
		return *m.PerUnit
	}
	return false
}

func (m *RegularChargeEntity) GetFixed() bool {
	if m != nil && m.Fixed != nil {
		return *m.Fixed
	}
	return false
}

func (m *RegularChargeEntity) GetMappedValues() []*EntityChargeMappedValue {
	if m != nil {
		return m.MappedValues
	}
	return nil
}

type RegularEnableEntity struct {
	Code       *string      `protobuf:"bytes,1,req,name=Code" json:"Code,omitempty"`
	EntityType *ENTITY_TYPE `protobuf:"varint,2,req,name=EntityType,enum=billing.ENTITY_TYPE" json:"EntityType,omitempty"`
	//required string EntityField=3;
	MappedValues         []*EntityEnableMappedValue `protobuf:"bytes,6,rep,name=MappedValues" json:"MappedValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RegularEnableEntity) Reset()         { *m = RegularEnableEntity{} }
func (m *RegularEnableEntity) String() string { return proto.CompactTextString(m) }
func (*RegularEnableEntity) ProtoMessage()    {}
func (*RegularEnableEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{24}
}

func (m *RegularEnableEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegularEnableEntity.Unmarshal(m, b)
}
func (m *RegularEnableEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegularEnableEntity.Marshal(b, m, deterministic)
}
func (m *RegularEnableEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegularEnableEntity.Merge(m, src)
}
func (m *RegularEnableEntity) XXX_Size() int {
	return xxx_messageInfo_RegularEnableEntity.Size(m)
}
func (m *RegularEnableEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_RegularEnableEntity.DiscardUnknown(m)
}

var xxx_messageInfo_RegularEnableEntity proto.InternalMessageInfo

func (m *RegularEnableEntity) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *RegularEnableEntity) GetEntityType() ENTITY_TYPE {
	if m != nil && m.EntityType != nil {
		return *m.EntityType
	}
	return ENTITY_TYPE_CTG_TYPE
}

func (m *RegularEnableEntity) GetMappedValues() []*EntityEnableMappedValue {
	if m != nil {
		return m.MappedValues
	}
	return nil
}

type CustTypeExtraSetting struct {
	CustType             *int64                 `protobuf:"varint,1,req,name=CustType" json:"CustType,omitempty"`
	CalcBase             *ChargeRegularCalcBase `protobuf:"varint,2,opt,name=CalcBase,enum=billing.ChargeRegularCalcBase" json:"CalcBase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CustTypeExtraSetting) Reset()         { *m = CustTypeExtraSetting{} }
func (m *CustTypeExtraSetting) String() string { return proto.CompactTextString(m) }
func (*CustTypeExtraSetting) ProtoMessage()    {}
func (*CustTypeExtraSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{25}
}

func (m *CustTypeExtraSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustTypeExtraSetting.Unmarshal(m, b)
}
func (m *CustTypeExtraSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustTypeExtraSetting.Marshal(b, m, deterministic)
}
func (m *CustTypeExtraSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustTypeExtraSetting.Merge(m, src)
}
func (m *CustTypeExtraSetting) XXX_Size() int {
	return xxx_messageInfo_CustTypeExtraSetting.Size(m)
}
func (m *CustTypeExtraSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_CustTypeExtraSetting.DiscardUnknown(m)
}

var xxx_messageInfo_CustTypeExtraSetting proto.InternalMessageInfo

func (m *CustTypeExtraSetting) GetCustType() int64 {
	if m != nil && m.CustType != nil {
		return *m.CustType
	}
	return 0
}

func (m *CustTypeExtraSetting) GetCalcBase() ChargeRegularCalcBase {
	if m != nil && m.CalcBase != nil {
		return *m.CalcBase
	}
	return ChargeRegularCalcBase_MAIN_CONNECTION
}

type RegularCharge struct {
	EffectiveDate           *timestamp.Timestamp    `protobuf:"bytes,1,req,name=EffectiveDate" json:"EffectiveDate,omitempty"`
	TransCode               *int64                  `protobuf:"varint,2,req,name=TransCode" json:"TransCode,omitempty"`
	TransSCode              *int64                  `protobuf:"varint,3,req,name=TransSCode" json:"TransSCode,omitempty"`
	TransTitle              *string                 `protobuf:"bytes,4,req,name=TransTitle" json:"TransTitle,omitempty"`
	TransSTitle             *string                 `protobuf:"bytes,5,opt,name=TransSTitle" json:"TransSTitle,omitempty"`
	IsChargable             *bool                   `protobuf:"varint,6,req,name=IsChargable" json:"IsChargable,omitempty"`
	ChargeCalcPeriod        *RegularChargePeriod    `protobuf:"varint,7,req,name=ChargeCalcPeriod,enum=billing.RegularChargePeriod" json:"ChargeCalcPeriod,omitempty"`
	ChargeInterval          *int64                  `protobuf:"varint,9,opt,name=ChargeInterval" json:"ChargeInterval,omitempty"`
	ChargeMonthlyDay        *int64                  `protobuf:"varint,10,opt,name=ChargeMonthlyDay" json:"ChargeMonthlyDay,omitempty"`
	ChargeType              *int64                  `protobuf:"varint,11,opt,name=ChargeType" json:"ChargeType,omitempty"`
	FixedCharge             *float64                `protobuf:"fixed64,12,opt,name=FixedCharge" json:"FixedCharge,omitempty"`
	FixedChargeDiscount     *float64                `protobuf:"fixed64,13,opt,name=FixedChargeDiscount" json:"FixedChargeDiscount,omitempty"`
	MinCharge               *float64                `protobuf:"fixed64,14,opt,name=MinCharge" json:"MinCharge,omitempty"`
	VatPercentage           *float64                `protobuf:"fixed64,15,opt,name=VatPercentage" json:"VatPercentage,omitempty"`
	RelationChargeEntity    *RegularChargeEntity    `protobuf:"bytes,16,opt,name=RelationChargeEntity" json:"RelationChargeEntity,omitempty"`
	RelationEnableEntity    *RegularEnableEntity    `protobuf:"bytes,17,opt,name=RelationEnableEntity" json:"RelationEnableEntity,omitempty"`
	Bypass                  *bool                   `protobuf:"varint,18,opt,name=Bypass" json:"Bypass,omitempty"`
	ExtraSettingPerCustType []*CustTypeExtraSetting `protobuf:"bytes,19,rep,name=ExtraSettingPerCustType" json:"ExtraSettingPerCustType,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                `json:"-"`
	XXX_unrecognized        []byte                  `json:"-"`
	XXX_sizecache           int32                   `json:"-"`
}

func (m *RegularCharge) Reset()         { *m = RegularCharge{} }
func (m *RegularCharge) String() string { return proto.CompactTextString(m) }
func (*RegularCharge) ProtoMessage()    {}
func (*RegularCharge) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{26}
}

func (m *RegularCharge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegularCharge.Unmarshal(m, b)
}
func (m *RegularCharge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegularCharge.Marshal(b, m, deterministic)
}
func (m *RegularCharge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegularCharge.Merge(m, src)
}
func (m *RegularCharge) XXX_Size() int {
	return xxx_messageInfo_RegularCharge.Size(m)
}
func (m *RegularCharge) XXX_DiscardUnknown() {
	xxx_messageInfo_RegularCharge.DiscardUnknown(m)
}

var xxx_messageInfo_RegularCharge proto.InternalMessageInfo

func (m *RegularCharge) GetEffectiveDate() *timestamp.Timestamp {
	if m != nil {
		return m.EffectiveDate
	}
	return nil
}

func (m *RegularCharge) GetTransCode() int64 {
	if m != nil && m.TransCode != nil {
		return *m.TransCode
	}
	return 0
}

func (m *RegularCharge) GetTransSCode() int64 {
	if m != nil && m.TransSCode != nil {
		return *m.TransSCode
	}
	return 0
}

func (m *RegularCharge) GetTransTitle() string {
	if m != nil && m.TransTitle != nil {
		return *m.TransTitle
	}
	return ""
}

func (m *RegularCharge) GetTransSTitle() string {
	if m != nil && m.TransSTitle != nil {
		return *m.TransSTitle
	}
	return ""
}

func (m *RegularCharge) GetIsChargable() bool {
	if m != nil && m.IsChargable != nil {
		return *m.IsChargable
	}
	return false
}

func (m *RegularCharge) GetChargeCalcPeriod() RegularChargePeriod {
	if m != nil && m.ChargeCalcPeriod != nil {
		return *m.ChargeCalcPeriod
	}
	return RegularChargePeriod_BILL
}

func (m *RegularCharge) GetChargeInterval() int64 {
	if m != nil && m.ChargeInterval != nil {
		return *m.ChargeInterval
	}
	return 0
}

func (m *RegularCharge) GetChargeMonthlyDay() int64 {
	if m != nil && m.ChargeMonthlyDay != nil {
		return *m.ChargeMonthlyDay
	}
	return 0
}

func (m *RegularCharge) GetChargeType() int64 {
	if m != nil && m.ChargeType != nil {
		return *m.ChargeType
	}
	return 0
}

func (m *RegularCharge) GetFixedCharge() float64 {
	if m != nil && m.FixedCharge != nil {
		return *m.FixedCharge
	}
	return 0
}

func (m *RegularCharge) GetFixedChargeDiscount() float64 {
	if m != nil && m.FixedChargeDiscount != nil {
		return *m.FixedChargeDiscount
	}
	return 0
}

func (m *RegularCharge) GetMinCharge() float64 {
	if m != nil && m.MinCharge != nil {
		return *m.MinCharge
	}
	return 0
}

func (m *RegularCharge) GetVatPercentage() float64 {
	if m != nil && m.VatPercentage != nil {
		return *m.VatPercentage
	}
	return 0
}

func (m *RegularCharge) GetRelationChargeEntity() *RegularChargeEntity {
	if m != nil {
		return m.RelationChargeEntity
	}
	return nil
}

func (m *RegularCharge) GetRelationEnableEntity() *RegularEnableEntity {
	if m != nil {
		return m.RelationEnableEntity
	}
	return nil
}

func (m *RegularCharge) GetBypass() bool {
	if m != nil && m.Bypass != nil {
		return *m.Bypass
	}
	return false
}

func (m *RegularCharge) GetExtraSettingPerCustType() []*CustTypeExtraSetting {
	if m != nil {
		return m.ExtraSettingPerCustType
	}
	return nil
}

type RegularChargeRequest struct {
	RegularCharge        []*RegularCharge `protobuf:"bytes,1,rep,name=RegularCharge" json:"RegularCharge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RegularChargeRequest) Reset()         { *m = RegularChargeRequest{} }
func (m *RegularChargeRequest) String() string { return proto.CompactTextString(m) }
func (*RegularChargeRequest) ProtoMessage()    {}
func (*RegularChargeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{27}
}

func (m *RegularChargeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegularChargeRequest.Unmarshal(m, b)
}
func (m *RegularChargeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegularChargeRequest.Marshal(b, m, deterministic)
}
func (m *RegularChargeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegularChargeRequest.Merge(m, src)
}
func (m *RegularChargeRequest) XXX_Size() int {
	return xxx_messageInfo_RegularChargeRequest.Size(m)
}
func (m *RegularChargeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegularChargeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegularChargeRequest proto.InternalMessageInfo

func (m *RegularChargeRequest) GetRegularCharge() []*RegularCharge {
	if m != nil {
		return m.RegularCharge
	}
	return nil
}

type SetupRequest struct {
	Tariffs              []*Tariff        `protobuf:"bytes,1,rep,name=Tariffs" json:"Tariffs,omitempty"`
	Ctgs                 []*Ctg           `protobuf:"bytes,2,rep,name=Ctgs" json:"Ctgs,omitempty"`
	RegularCharge        []*RegularCharge `protobuf:"bytes,3,rep,name=RegularCharge" json:"RegularCharge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SetupRequest) Reset()         { *m = SetupRequest{} }
func (m *SetupRequest) String() string { return proto.CompactTextString(m) }
func (*SetupRequest) ProtoMessage()    {}
func (*SetupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{28}
}

func (m *SetupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetupRequest.Unmarshal(m, b)
}
func (m *SetupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetupRequest.Marshal(b, m, deterministic)
}
func (m *SetupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetupRequest.Merge(m, src)
}
func (m *SetupRequest) XXX_Size() int {
	return xxx_messageInfo_SetupRequest.Size(m)
}
func (m *SetupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetupRequest proto.InternalMessageInfo

func (m *SetupRequest) GetTariffs() []*Tariff {
	if m != nil {
		return m.Tariffs
	}
	return nil
}

func (m *SetupRequest) GetCtgs() []*Ctg {
	if m != nil {
		return m.Ctgs
	}
	return nil
}

func (m *SetupRequest) GetRegularCharge() []*RegularCharge {
	if m != nil {
		return m.RegularCharge
	}
	return nil
}

func init() {
	proto.RegisterEnum("billing.SERVICE_TYPE", SERVICE_TYPE_name, SERVICE_TYPE_value)
	proto.RegisterEnum("billing.CONNECTION_STATUS_TYPE", CONNECTION_STATUS_TYPE_name, CONNECTION_STATUS_TYPE_value)
	proto.RegisterEnum("billing.READING_TYPE", READING_TYPE_name, READING_TYPE_value)
	proto.RegisterEnum("billing.RegularChargePeriod", RegularChargePeriod_name, RegularChargePeriod_value)
	proto.RegisterEnum("billing.ENTITY_TYPE", ENTITY_TYPE_name, ENTITY_TYPE_value)
	proto.RegisterEnum("billing.ChargeRegularCalcBase", ChargeRegularCalcBase_name, ChargeRegularCalcBase_value)
	proto.RegisterType((*Meter)(nil), "billing.Meter")
	proto.RegisterType((*Connection)(nil), "billing.Connection")
	proto.RegisterType((*SubConnection)(nil), "billing.SubConnection")
	proto.RegisterType((*Service)(nil), "billing.Service")
	proto.RegisterType((*Property)(nil), "billing.Property")
	proto.RegisterType((*Customer)(nil), "billing.Customer")
	proto.RegisterType((*Reading)(nil), "billing.Reading")
	proto.RegisterType((*ServiceReading)(nil), "billing.ServiceReading")
	proto.RegisterType((*BillRequest)(nil), "billing.BillRequest")
	proto.RegisterType((*ExtraCharge)(nil), "billing.ExtraCharge")
	proto.RegisterType((*BillResponceItemCtg)(nil), "billing.BillResponceItemCtg")
	proto.RegisterType((*BillResponceItem)(nil), "billing.BillResponceItem")
	proto.RegisterType((*BillResponce)(nil), "billing.BillResponce")
	proto.RegisterType((*ServiceTariff)(nil), "billing.ServiceTariff")
	proto.RegisterType((*Ctg)(nil), "billing.Ctg")
	proto.RegisterType((*CtgRequest)(nil), "billing.CtgRequest")
	proto.RegisterType((*ExtraTariffFess)(nil), "billing.ExtraTariffFess")
	proto.RegisterType((*TariffBand)(nil), "billing.TariffBand")
	proto.RegisterType((*Tariff)(nil), "billing.Tariff")
	proto.RegisterType((*TariffRequest)(nil), "billing.TariffRequest")
	proto.RegisterType((*Empty)(nil), "billing.Empty")
	proto.RegisterType((*EntityChargeMappedValue)(nil), "billing.EntityChargeMappedValue")
	proto.RegisterType((*EntityEnableMappedValue)(nil), "billing.EntityEnableMappedValue")
	proto.RegisterType((*RegularChargeEntity)(nil), "billing.RegularChargeEntity")
	proto.RegisterType((*RegularEnableEntity)(nil), "billing.RegularEnableEntity")
	proto.RegisterType((*CustTypeExtraSetting)(nil), "billing.CustTypeExtraSetting")
	proto.RegisterType((*RegularCharge)(nil), "billing.RegularCharge")
	proto.RegisterType((*RegularChargeRequest)(nil), "billing.RegularChargeRequest")
	proto.RegisterType((*SetupRequest)(nil), "billing.SetupRequest")
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba) }

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 2167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x4d, 0x6f, 0xe3, 0xc8,
	0xd1, 0x1e, 0xea, 0xdb, 0x25, 0x59, 0xe6, 0xb4, 0x3d, 0x1e, 0xae, 0xdf, 0xd9, 0x19, 0x81, 0xef,
	0x22, 0xf0, 0x1a, 0x1b, 0xcf, 0xac, 0xec, 0xd9, 0x04, 0x8b, 0x60, 0x11, 0x9a, 0xa2, 0x6d, 0x62,
	0x64, 0x59, 0x68, 0xd1, 0x1e, 0x18, 0x39, 0x18, 0x1c, 0xa9, 0xad, 0x25, 0x56, 0x22, 0x15, 0x92,
	0x9a, 0x8c, 0x90, 0x5b, 0x2e, 0xb9, 0xe4, 0x0f, 0xe4, 0x16, 0x20, 0xc8, 0x31, 0xc7, 0x20, 0xa7,
	0xfc, 0x8a, 0x20, 0xc7, 0xe4, 0x87, 0xe4, 0x14, 0xf4, 0x07, 0xc9, 0x96, 0x28, 0x7b, 0xb3, 0x83,
	0xdc, 0x58, 0x4f, 0x55, 0x57, 0x77, 0x3f, 0x55, 0xd5, 0x55, 0x12, 0x6c, 0xcf, 0xc2, 0x20, 0x0e,
	0x5e, 0x46, 0x24, 0x7c, 0xef, 0x0d, 0xc9, 0x21, 0x93, 0x50, 0xf5, 0x9d, 0x37, 0x99, 0x78, 0xfe,
	0x78, 0xef, 0xc5, 0x38, 0x08, 0xc6, 0x13, 0xf2, 0x92, 0xc1, 0xef, 0xe6, 0x77, 0x2f, 0x63, 0x6f,
	0x4a, 0xa2, 0xd8, 0x9d, 0xce, 0xb8, 0xa5, 0xfe, 0x5b, 0x05, 0xca, 0x17, 0x24, 0x26, 0x21, 0x7a,
	0x06, 0x1b, 0xec, 0xc3, 0x59, 0xcc, 0x88, 0xa6, 0xb4, 0x0a, 0xfb, 0x1b, 0x38, 0x03, 0xd0, 0x1e,
	0xd4, 0x98, 0x80, 0xc9, 0x9d, 0x56, 0x60, 0xca, 0x54, 0xa6, 0xba, 0x8e, 0xe7, 0x4e, 0xa9, 0xa8,
	0x15, 0x5b, 0x85, 0xfd, 0x22, 0x4e, 0x65, 0xb4, 0x0f, 0x5b, 0x66, 0xe0, 0xbf, 0x27, 0x61, 0x4c,
	0xc2, 0x53, 0x77, 0x18, 0x07, 0xa1, 0x56, 0x6a, 0x29, 0xfb, 0x45, 0xbc, 0x0a, 0xeb, 0x7f, 0x2f,
	0x00, 0x98, 0x81, 0xef, 0x93, 0x61, 0xec, 0x05, 0x3e, 0xda, 0x81, 0xb2, 0x29, 0x1d, 0x85, 0x0b,
	0x48, 0x83, 0x6a, 0x2f, 0xb8, 0xf2, 0xbd, 0x38, 0x62, 0xa7, 0x28, 0xe2, 0x44, 0x44, 0x2d, 0xa8,
	0xdb, 0xd1, 0xc9, 0x7c, 0xf2, 0xdd, 0x85, 0x38, 0x87, 0xb2, 0x5f, 0xc3, 0x32, 0x84, 0x74, 0x68,
	0x50, 0xff, 0xe9, 0x51, 0xf9, 0x39, 0x96, 0x30, 0xf4, 0x99, 0x60, 0x43, 0x2b, 0xb7, 0x94, 0xfd,
	0x7a, 0xbb, 0x79, 0x28, 0x88, 0x3c, 0xe4, 0x97, 0xcd, 0xa8, 0xb2, 0xa2, 0xd8, 0x9b, 0x9a, 0x81,
	0x1f, 0x69, 0x95, 0x96, 0xb2, 0xaf, 0xe0, 0x0c, 0x40, 0x6f, 0x40, 0xcd, 0xee, 0x31, 0x88, 0xdd,
	0x78, 0x1e, 0x69, 0xd5, 0x96, 0xb2, 0xdf, 0x6c, 0xbf, 0x48, 0xdd, 0x99, 0x97, 0xbd, 0x9e, 0x65,
	0x3a, 0xf6, 0x65, 0xef, 0x76, 0xe0, 0x18, 0xce, 0xd5, 0xe0, 0xd6, 0xb9, 0xe9, 0x5b, 0x38, 0xb7,
	0x10, 0x7d, 0x03, 0xcd, 0xc1, 0xfc, 0x5d, 0x06, 0x47, 0x5a, 0xad, 0x55, 0xdc, 0xaf, 0xb7, 0x77,
	0x53, 0x57, 0x4b, 0x6a, 0xbc, 0x62, 0xad, 0xff, 0x45, 0x81, 0xcd, 0x25, 0xe8, 0x1e, 0x62, 0xbf,
	0x81, 0x3d, 0x76, 0x03, 0x37, 0x26, 0xf4, 0x12, 0xf3, 0xe9, 0x8c, 0x1a, 0xf7, 0x49, 0x48, 0xd9,
	0xd5, 0x0a, 0xec, 0x8e, 0x0f, 0x58, 0xa0, 0x63, 0x78, 0xb2, 0x8c, 0x0e, 0x89, 0x1f, 0xbb, 0x63,
	0xc2, 0x02, 0xa1, 0xe0, 0xf5, 0x4a, 0x39, 0x9c, 0x3c, 0x1a, 0x89, 0xa8, 0xff, 0x0a, 0xaa, 0x03,
	0x9e, 0xd2, 0xe8, 0x27, 0x50, 0x17, 0x9f, 0xe9, 0xb1, 0x9b, 0xed, 0x27, 0xd9, 0xfd, 0x2d, 0x7c,
	0x6d, 0x9b, 0x16, 0x27, 0x50, 0xb6, 0x44, 0x47, 0x72, 0x42, 0xb1, 0x7c, 0xa9, 0xb7, 0xb7, 0xb3,
	0x10, 0x64, 0xa4, 0x49, 0x66, 0xfa, 0x1f, 0x0a, 0x50, 0xeb, 0x87, 0xc1, 0x8c, 0x84, 0xf1, 0x82,
	0x9e, 0x8f, 0x7e, 0xd3, 0xa4, 0xe7, 0x6c, 0x25, 0x22, 0x4d, 0x01, 0xdb, 0xbf, 0x0b, 0x4e, 0x27,
	0xee, 0xf8, 0x4b, 0x76, 0xc7, 0x0d, 0x9c, 0x01, 0xb2, 0xb6, 0xcd, 0x6e, 0x26, 0x69, 0xdb, 0xb2,
	0xf6, 0x88, 0x25, 0x9a, 0xa4, 0x3d, 0x92, 0xb5, 0xc7, 0x2c, 0xb9, 0x24, 0xed, 0xb1, 0xac, 0x7d,
	0xcd, 0xb2, 0x4a, 0xd2, 0xbe, 0xe6, 0x7c, 0xe2, 0x20, 0x98, 0xd2, 0x34, 0x11, 0x7c, 0x32, 0x11,
	0x7d, 0x01, 0x35, 0x41, 0x4d, 0xa4, 0x6d, 0xb0, 0x0c, 0x52, 0x33, 0x06, 0xb9, 0x02, 0xa7, 0x16,
	0x6c, 0x97, 0xe8, 0xda, 0x1d, 0xba, 0x31, 0x19, 0x69, 0xc0, 0x4a, 0x29, 0x03, 0xf4, 0x3f, 0x16,
	0xa0, 0x66, 0xce, 0xa3, 0x38, 0x98, 0x92, 0x90, 0x6e, 0x49, 0xbf, 0xbf, 0x23, 0x8b, 0x84, 0x22,
	0x21, 0xd2, 0x67, 0x81, 0x7e, 0xb2, 0xa0, 0xf1, 0x62, 0x4d, 0x65, 0xbe, 0x81, 0x19, 0x4c, 0x67,
	0xae, 0xbf, 0x10, 0xb5, 0x9a, 0x01, 0xcb, 0xe4, 0x96, 0x1e, 0x24, 0xb7, 0xfc, 0x20, 0xb9, 0x95,
	0x07, 0xc9, 0xad, 0x3e, 0x48, 0x6e, 0x6d, 0x95, 0xdc, 0x1f, 0x67, 0x89, 0xa1, 0x6d, 0xb0, 0xe7,
	0xe1, 0x71, 0x4a, 0x61, 0xa2, 0xc0, 0xa9, 0x89, 0xfe, 0x9b, 0x02, 0x54, 0x31, 0x71, 0x47, 0x9e,
	0x3f, 0x66, 0x24, 0xf1, 0x02, 0x60, 0x24, 0x29, 0x38, 0x11, 0x69, 0x72, 0x0b, 0xa3, 0x94, 0x27,
	0x39, 0xb9, 0xb1, 0x65, 0x74, 0xec, 0xde, 0x99, 0x48, 0x6e, 0xc9, 0x92, 0x9e, 0xb5, 0x1f, 0x0a,
	0x40, 0x14, 0x59, 0x06, 0x50, 0xad, 0x99, 0x6a, 0x4b, 0x5c, 0x9b, 0x02, 0xe8, 0x08, 0xaa, 0x7d,
	0x7c, 0xdb, 0x31, 0x1c, 0x4b, 0xbc, 0x73, 0x7b, 0x87, 0xbc, 0x4f, 0x1c, 0x26, 0x7d, 0xe2, 0xd0,
	0x49, 0xfa, 0x04, 0xae, 0xf4, 0x31, 0xb5, 0xa4, 0x8b, 0x4c, 0xb1, 0xa8, 0xf2, 0xfd, 0x8b, 0x4c,
	0xb6, 0x48, 0x9f, 0x43, 0x33, 0xc9, 0x2e, 0xb1, 0xf7, 0x47, 0x57, 0xf3, 0x41, 0x4a, 0xa7, 0x28,
	0xe5, 0x2c, 0x81, 0x05, 0x8e, 0x13, 0x03, 0xfd, 0xcf, 0x0a, 0xd4, 0x4f, 0xbc, 0xc9, 0x04, 0x93,
	0x5f, 0xce, 0x49, 0x14, 0xd3, 0xd0, 0x25, 0x09, 0xcb, 0x76, 0x94, 0x43, 0x97, 0x28, 0x70, 0x96,
	0xd3, 0x26, 0xa8, 0x49, 0x29, 0x08, 0x8f, 0xb4, 0xdd, 0xd0, 0xa2, 0x79, 0x9a, 0x2b, 0x1a, 0xb1,
	0x75, 0x6e, 0x01, 0x3a, 0x00, 0xd5, 0x1e, 0xfb, 0x41, 0x48, 0x28, 0x2b, 0xd6, 0xdd, 0x1d, 0x19,
	0xc6, 0xac, 0x3b, 0xd6, 0x70, 0x0e, 0xd7, 0x7f, 0x01, 0x75, 0xeb, 0x43, 0x1c, 0xba, 0xe6, 0xb7,
	0x6e, 0x38, 0x26, 0xb4, 0x97, 0x75, 0xac, 0x81, 0x89, 0xed, 0x3e, 0xed, 0x10, 0x9a, 0xc2, 0x32,
	0x51, 0x86, 0x10, 0x82, 0x92, 0x19, 0x8c, 0x88, 0x68, 0xc5, 0xec, 0x1b, 0xed, 0x42, 0xc5, 0x98,
	0x06, 0x73, 0x9f, 0x6f, 0xa3, 0x60, 0x21, 0xe9, 0x2e, 0x6c, 0x73, 0x2e, 0xa2, 0x59, 0xe0, 0x0f,
	0x89, 0x1d, 0x93, 0xa9, 0x19, 0x8f, 0x97, 0xfb, 0x80, 0x92, 0xf4, 0x81, 0xcc, 0x49, 0x41, 0x76,
	0x42, 0x13, 0xca, 0x71, 0x3f, 0xa4, 0xfe, 0x59, 0x42, 0xa5, 0x80, 0xfe, 0x37, 0x05, 0xd4, 0xd5,
	0x3d, 0x3e, 0x3e, 0xd2, 0x5f, 0x41, 0x95, 0x13, 0x91, 0xb0, 0xfe, 0x2c, 0x5d, 0xb4, 0xe6, 0x22,
	0x38, 0x31, 0x46, 0x3f, 0x85, 0x86, 0xc4, 0x62, 0xa4, 0x0d, 0xd9, 0xe2, 0x9d, 0x74, 0xb1, 0xa4,
	0xc4, 0x4b, 0x96, 0xba, 0x09, 0x0d, 0xd9, 0x33, 0xcb, 0x75, 0xe1, 0x44, 0x61, 0x4e, 0x3e, 0xb9,
	0xf7, 0x04, 0xe9, 0xf6, 0xfa, 0x3b, 0xd8, 0x4c, 0x6e, 0xe1, 0x86, 0xde, 0xdd, 0xdd, 0xc7, 0x13,
	0xa0, 0x41, 0x95, 0xb9, 0xb0, 0x47, 0x22, 0xc0, 0x89, 0xa8, 0x5f, 0x40, 0x31, 0x17, 0xbb, 0xb4,
	0x87, 0xbf, 0x12, 0xcb, 0xee, 0x12, 0xde, 0x76, 0x57, 0xb3, 0x95, 0xab, 0x71, 0x62, 0xa6, 0x1f,
	0x02, 0x50, 0x06, 0x45, 0x95, 0xb4, 0xa0, 0x64, 0xc6, 0x69, 0xaa, 0x37, 0xb2, 0x0a, 0x89, 0xc7,
	0x98, 0x69, 0x68, 0x9c, 0xb7, 0x18, 0x71, 0xdc, 0xc1, 0x29, 0x89, 0xa2, 0x34, 0x15, 0x15, 0x29,
	0x15, 0x69, 0x02, 0x93, 0x68, 0x18, 0x7a, 0x33, 0xd1, 0x7a, 0x79, 0x02, 0x67, 0x10, 0xfa, 0x11,
	0x34, 0x79, 0xee, 0xf4, 0x49, 0x98, 0x4d, 0x6c, 0x0a, 0x5e, 0x41, 0x69, 0x15, 0xa5, 0x48, 0x32,
	0x52, 0xf0, 0xf7, 0x2c, 0x87, 0xd3, 0x5d, 0x4f, 0xbd, 0x0f, 0x64, 0x24, 0xb2, 0xb4, 0xcc, 0xcc,
	0x64, 0x48, 0x1f, 0x01, 0xf0, 0x93, 0x9f, 0xb8, 0xfe, 0x88, 0x9e, 0xfc, 0x34, 0x0c, 0xa6, 0xa2,
	0x00, 0xd8, 0x37, 0x6a, 0x42, 0xc1, 0x09, 0x44, 0xee, 0x17, 0x9c, 0x80, 0x35, 0xb1, 0xc0, 0x8f,
	0x62, 0x37, 0x2d, 0xab, 0x54, 0xa6, 0xb5, 0x92, 0x8e, 0xb4, 0xac, 0x56, 0xc4, 0x24, 0xfb, 0x4f,
	0x05, 0x2a, 0x22, 0x05, 0xf6, 0xa0, 0xc6, 0xbf, 0xec, 0x91, 0x20, 0x28, 0x95, 0xd1, 0x67, 0xb0,
	0xe9, 0xb8, 0x1f, 0xa4, 0x7b, 0xf1, 0x29, 0x6b, 0x19, 0x44, 0x87, 0x80, 0x3a, 0x5e, 0x34, 0x5c,
	0xa1, 0x80, 0x93, 0xb5, 0x46, 0x83, 0xbe, 0x82, 0x0d, 0x16, 0xa1, 0x53, 0x42, 0xe8, 0x50, 0x45,
	0x23, 0xa9, 0x2d, 0x57, 0x40, 0x16, 0x3b, 0x9c, 0x99, 0xa2, 0xcf, 0xa1, 0x4c, 0x49, 0x89, 0xb4,
	0x32, 0x5b, 0x93, 0xcd, 0x49, 0x19, 0x61, 0x98, 0x5b, 0xe8, 0x5f, 0xd3, 0x83, 0xb3, 0x44, 0x12,
	0x89, 0xf3, 0x79, 0x96, 0x78, 0xbc, 0x5c, 0xb6, 0x56, 0x56, 0x67, 0x19, 0x57, 0x85, 0xb2, 0x35,
	0x9d, 0xc5, 0x0b, 0xdd, 0x83, 0xa7, 0x96, 0x1f, 0x7b, 0xf1, 0x82, 0x97, 0xcf, 0x85, 0x3b, 0x9b,
	0x91, 0xd1, 0xb5, 0x3b, 0x99, 0x13, 0x29, 0x2e, 0x4a, 0x2e, 0x2e, 0x8a, 0x88, 0xcb, 0x0e, 0x94,
	0xbb, 0xf3, 0x37, 0x64, 0x21, 0x66, 0x2f, 0x2e, 0x50, 0x94, 0xb9, 0x10, 0x29, 0xc2, 0x05, 0xdd,
	0x4a, 0xb6, 0xb2, 0x7c, 0xf7, 0xdd, 0x64, 0x69, 0x2b, 0xc9, 0x4d, 0xe1, 0x1e, 0x37, 0xb5, 0xc4,
	0xcd, 0x3f, 0x14, 0xd8, 0xc6, 0x64, 0x3c, 0x9f, 0xb8, 0x21, 0x3f, 0x33, 0x77, 0xba, 0xb6, 0x00,
	0x8e, 0x01, 0xb8, 0x56, 0xea, 0xea, 0xd2, 0x43, 0xd4, 0x73, 0x6c, 0xe7, 0x86, 0x17, 0xbe, 0x64,
	0xc7, 0xc6, 0x4d, 0x31, 0x71, 0xf3, 0x9d, 0x13, 0x91, 0x9e, 0x88, 0xe5, 0x31, 0x4b, 0xea, 0x1a,
	0xe6, 0x02, 0xea, 0x40, 0x43, 0xba, 0x0c, 0xfd, 0x29, 0x42, 0xc9, 0x6f, 0x65, 0xfb, 0xac, 0x27,
	0x18, 0x2f, 0xad, 0xd2, 0xff, 0x94, 0xdd, 0x8b, 0x13, 0xf4, 0x3f, 0xbf, 0xd7, 0x7f, 0x77, 0xce,
	0x5c, 0x74, 0x56, 0xce, 0xe9, 0xc3, 0x4e, 0x32, 0x3f, 0xb2, 0xb4, 0x1d, 0x90, 0x38, 0xa6, 0x13,
	0x85, 0x3c, 0x67, 0x2a, 0x2b, 0x73, 0xe6, 0xd7, 0x50, 0x33, 0xdd, 0xc9, 0xf0, 0xc4, 0x8d, 0x78,
	0x79, 0x35, 0xdb, 0xcf, 0xb3, 0x67, 0x8d, 0x77, 0x02, 0x11, 0x51, 0x61, 0x85, 0x53, 0x7b, 0xfd,
	0x5f, 0x15, 0xd8, 0x5c, 0x8a, 0x37, 0xfa, 0x39, 0x6c, 0xf2, 0x86, 0xed, 0xbd, 0x27, 0x1d, 0x37,
	0x26, 0x62, 0x96, 0x78, 0x68, 0x10, 0x5a, 0x5e, 0xc0, 0xda, 0x68, 0xe8, 0xfa, 0x51, 0xda, 0xbc,
	0x8b, 0x38, 0x03, 0xd0, 0x73, 0x00, 0x26, 0x0c, 0x98, 0x9a, 0xff, 0x94, 0x96, 0x90, 0x54, 0xef,
	0x78, 0xf1, 0x84, 0xb0, 0x47, 0x67, 0x03, 0x4b, 0x08, 0x7d, 0x00, 0xb9, 0x35, 0x37, 0xe0, 0xb3,
	0xb1, 0x0c, 0xf1, 0x5f, 0xc9, 0xec, 0x36, 0x94, 0x6b, 0xad, 0xc2, 0xe6, 0x11, 0x19, 0x42, 0xe7,
	0xa0, 0xf2, 0xdb, 0x52, 0x1e, 0xfa, 0x24, 0xf4, 0x82, 0x91, 0x56, 0x65, 0x71, 0x7e, 0x26, 0xcd,
	0x5b, 0x12, 0x2b, 0xdc, 0x06, 0xe7, 0x56, 0xd1, 0x27, 0x9e, 0x63, 0xb6, 0x1f, 0x93, 0xf0, 0xbd,
	0x3b, 0x61, 0x53, 0x73, 0x11, 0xaf, 0xa0, 0xf4, 0x89, 0x17, 0x29, 0x1a, 0xf8, 0xf1, 0xb7, 0x93,
	0x45, 0xc7, 0x5d, 0xb0, 0xdf, 0x1c, 0x45, 0x9c, 0xc3, 0x29, 0x03, 0x1c, 0x63, 0xd1, 0xae, 0x33,
	0x2b, 0x09, 0x49, 0x5b, 0x00, 0x87, 0xb4, 0x86, 0xd4, 0x02, 0x44, 0x0c, 0x5f, 0xc1, 0xb6, 0x24,
	0x26, 0x0f, 0xa8, 0xb6, 0xc9, 0x2c, 0xd7, 0xa9, 0xd8, 0x1f, 0x23, 0x9e, 0x2f, 0x3c, 0x36, 0xf9,
	0xe8, 0x93, 0x02, 0xf4, 0x15, 0xbf, 0x76, 0xe5, 0xa7, 0x79, 0x8b, 0xbf, 0xe2, 0x4b, 0x20, 0xea,
	0xc3, 0x0e, 0x26, 0x13, 0x97, 0xb6, 0x3e, 0xf9, 0xed, 0xd0, 0x54, 0x36, 0x49, 0xdf, 0xc3, 0x2c,
	0xb7, 0xc1, 0x6b, 0x57, 0xca, 0x1e, 0xe5, 0xaa, 0xd5, 0x1e, 0xaf, 0xf7, 0x28, 0xdb, 0xe0, 0xb5,
	0x2b, 0x69, 0x3b, 0x3b, 0x59, 0xcc, 0xdc, 0x28, 0xd2, 0x10, 0x7b, 0x64, 0x84, 0x84, 0xde, 0xc2,
	0x53, 0xb9, 0xde, 0xfa, 0x24, 0x4c, 0xcb, 0x6d, 0x9b, 0x15, 0xf2, 0xa7, 0x4b, 0xb3, 0xf4, 0x6a,
	0x7d, 0xe2, 0xfb, 0x56, 0xeb, 0x0e, 0xbd, 0x82, 0x74, 0xdf, 0xa4, 0x9d, 0xfc, 0x6c, 0xa5, 0xee,
	0x44, 0x53, 0xd9, 0x5d, 0xcf, 0x12, 0x5e, 0x36, 0xd6, 0x7f, 0xaf, 0x40, 0x63, 0x40, 0xe2, 0xf9,
	0xec, 0x87, 0x77, 0xa7, 0xef, 0x9f, 0x80, 0xf2, 0x67, 0x2b, 0xfe, 0x80, 0xb3, 0x1d, 0x5c, 0x41,
	0x43, 0x9e, 0xfa, 0xd0, 0x06, 0x94, 0xdf, 0x1a, 0x8e, 0x85, 0xd5, 0x47, 0xf4, 0x73, 0x60, 0xbd,
	0xb5, 0xb0, 0xaa, 0xa0, 0x2d, 0xa8, 0x5b, 0x5d, 0xcb, 0x74, 0xb0, 0x6d, 0xda, 0xce, 0x8d, 0x5a,
	0x40, 0x55, 0x28, 0x9e, 0x19, 0x03, 0xb5, 0x88, 0xea, 0x50, 0x3d, 0xbf, 0xe9, 0x60, 0xa3, 0xe7,
	0xa8, 0x25, 0x54, 0x83, 0xd2, 0xa9, 0x8d, 0x2d, 0xb5, 0x7c, 0xf0, 0x3b, 0x05, 0x76, 0xd7, 0xff,
	0xa3, 0x84, 0xfe, 0x0f, 0x9e, 0x0a, 0x8d, 0xd5, 0xb9, 0x7d, 0x6b, 0x3b, 0xe7, 0x97, 0x57, 0xce,
	0xed, 0x85, 0xc5, 0xf7, 0xd4, 0x60, 0x67, 0x59, 0x29, 0x34, 0x0a, 0x5d, 0xd6, 0xb1, 0x07, 0x6b,
	0x95, 0x05, 0xf4, 0x1c, 0xf6, 0x72, 0xca, 0xcc, 0x6d, 0xf1, 0xe0, 0x35, 0x34, 0xe4, 0xdf, 0xad,
	0x08, 0xa0, 0x62, 0x98, 0xce, 0x95, 0xd1, 0x55, 0x1f, 0xd1, 0x1b, 0x18, 0xd7, 0x16, 0x36, 0xce,
	0x2c, 0x55, 0x41, 0x0d, 0xa8, 0x59, 0x03, 0xc7, 0xbe, 0x30, 0x1c, 0x4b, 0x2d, 0x1c, 0x7c, 0xb1,
	0xd2, 0x5e, 0xc5, 0x33, 0x52, 0x83, 0xd2, 0x89, 0xdd, 0xed, 0xaa, 0x0a, 0x5d, 0x7b, 0x71, 0xd9,
	0x73, 0xce, 0xbb, 0x37, 0x6a, 0xe1, 0xe0, 0xdf, 0x05, 0xa8, 0x4b, 0xfd, 0x86, 0xfa, 0x32, 0x1d,
	0xbe, 0xa1, 0xaa, 0xa0, 0xc7, 0xb0, 0x69, 0x5e, 0x0d, 0x9c, 0xcb, 0x0b, 0x0b, 0x73, 0xa8, 0x80,
	0x10, 0x34, 0x53, 0xe8, 0xb4, 0x6b, 0x9c, 0x7d, 0xa9, 0x16, 0x73, 0x58, 0x5b, 0x2d, 0xe5, 0xb0,
	0x23, 0xb5, 0x9c, 0xc3, 0x8e, 0xd5, 0x4a, 0x0e, 0x7b, 0xad, 0x56, 0xd1, 0x0e, 0xa8, 0x7d, 0x7c,
	0xd9, 0xb7, 0xb0, 0x73, 0x73, 0x7b, 0x6d, 0x98, 0x86, 0x63, 0x75, 0xd4, 0x1a, 0xb5, 0x4c, 0x51,
	0xbe, 0xf3, 0x46, 0x0e, 0x6b, 0xab, 0x90, 0xc3, 0x8e, 0xd4, 0x7a, 0x0e, 0x3b, 0x56, 0x1b, 0x39,
	0xec, 0xb5, 0xba, 0x89, 0x9e, 0xc2, 0xb6, 0x94, 0x01, 0x1d, 0xdb, 0xe0, 0xc1, 0x68, 0xa2, 0x27,
	0xf0, 0x38, 0x97, 0x1a, 0xea, 0x96, 0x94, 0x17, 0x14, 0xb6, 0x07, 0x27, 0x57, 0xdd, 0x37, 0x22,
	0x80, 0x2a, 0xdd, 0x80, 0x7d, 0x66, 0x7e, 0x1e, 0x53, 0xf2, 0x45, 0xea, 0xaa, 0xe8, 0xe0, 0xaf,
	0x0a, 0x3c, 0x59, 0xdb, 0x3e, 0xd1, 0x36, 0x6c, 0x5d, 0x18, 0x76, 0xef, 0x36, 0x73, 0xae, 0x2a,
	0x68, 0x17, 0x90, 0xd1, 0xed, 0xde, 0x0e, 0xae, 0x4e, 0x64, 0xbc, 0x80, 0xfe, 0x1f, 0x5e, 0x9c,
	0xdb, 0xd6, 0xd9, 0xf9, 0x6d, 0xdf, 0xc2, 0xa6, 0xd5, 0x73, 0x8c, 0x33, 0x6b, 0xd5, 0xa8, 0x88,
	0x3e, 0x85, 0x4f, 0xba, 0x97, 0x6f, 0x65, 0x13, 0x49, 0x5d, 0xa2, 0x39, 0x7c, 0x6a, 0xe3, 0x81,
	0xb3, 0xba, 0xb0, 0x4c, 0x8f, 0xd2, 0x35, 0x06, 0x8e, 0x0c, 0x56, 0xda, 0xbf, 0x86, 0xe6, 0x09,
	0xaf, 0xd4, 0xec, 0xef, 0xc5, 0x8a, 0x78, 0xca, 0x77, 0x56, 0x7e, 0xe4, 0xb1, 0xe7, 0x63, 0xef,
	0xc9, 0xda, 0x9f, 0x7e, 0xfa, 0x23, 0xf4, 0x0a, 0xca, 0xec, 0x9d, 0x41, 0xd2, 0x4f, 0x3a, 0xe9,
	0xdd, 0xd9, 0xcb, 0xfe, 0x3c, 0xe6, 0x13, 0xef, 0xa3, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x66,
	0x79, 0x37, 0x86, 0xac, 0x17, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BillingServiceClient interface {
	Charge(ctx context.Context, in *BillRequest, opts ...grpc.CallOption) (*BillResponce, error)
	Setup(ctx context.Context, in *SetupRequest, opts ...grpc.CallOption) (*Empty, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) Charge(ctx context.Context, in *BillRequest, opts ...grpc.CallOption) (*BillResponce, error) {
	out := new(BillResponce)
	err := c.cc.Invoke(ctx, "/billing.BillingService/Charge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) Setup(ctx context.Context, in *SetupRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/billing.BillingService/Setup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
type BillingServiceServer interface {
	Charge(context.Context, *BillRequest) (*BillResponce, error)
	Setup(context.Context, *SetupRequest) (*Empty, error)
}

// UnimplementedBillingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBillingServiceServer struct {
}

func (*UnimplementedBillingServiceServer) Charge(ctx context.Context, req *BillRequest) (*BillResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Charge not implemented")
}
func (*UnimplementedBillingServiceServer) Setup(ctx context.Context, req *SetupRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Setup not implemented")
}

func RegisterBillingServiceServer(s *grpc.Server, srv BillingServiceServer) {
	s.RegisterService(&_BillingService_serviceDesc, srv)
}

func _BillingService_Charge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).Charge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.BillingService/Charge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).Charge(ctx, req.(*BillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_Setup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).Setup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.BillingService/Setup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).Setup(ctx, req.(*SetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BillingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "billing.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Charge",
			Handler:    _BillingService_Charge_Handler,
		},
		{
			MethodName: "Setup",
			Handler:    _BillingService_Setup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
